#!/usr/bin/env bash

source /usr/lib/powerdown-functions

case "$@" in
  --hibernate | --suspend-hybrid)
        if can_suspend_to_disk; then
            exit 0
        else
            exit 1
        fi
    ;;
  --suspend)
    exit 0
    ;;
  *)
    echo "[powerdown] pm-is-supported [ --hibernate | --suspend ]"
    exit 1;
    ;;
esac
