#!/usr/bin/env bash

case "$@" in
  --hibernate)
        if [[ -f /hibernate ]]; then
            exit 0
        else
            exit 1
        fi
    ;;
  --suspend)
    exit 0
    ;;
  *)
    echo "[powerdown] pm-is-supported [ --hibernate | --suspend ]"
    exit 1;
    ;;
esac
