#!/usr/bin/env bash
# powerdown - powerup
#

if [[ $EUID != 0 ]]; then
  echo "[powerdown] must be run as root"
  exit 1
fi

source /usr/lib/powerdown-functions

lock

# bus
for i in /sys/bus/{pci,usb}/devices/*/power/control; do opt "$i" on; done

# usb autosuspend
for i in /sys/bus/usb/devices/*/power/autosuspend; do opt "$i" 600; done

# nmi_watchdog
opt /proc/sys/kernel/nmi_watchdog 1

# cpu
load_mod acpi_cpufreq
for i in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do opt "$i" ondemand; done

# aspm
opt /sys/module/pcie_aspm/parameters/policy default

# kernel write mode
opt /proc/sys/vm/laptop_mode 0
opt /proc/sys/vm/dirty_ratio 30
opt /proc/sys/vm/dirty_background_ratio 10
opt /proc/sys/vm/dirty_expire_centisecs 600
opt /proc/sys/vm/dirty_writeback_centisecs 600

# Disk powersave
for i in /sys/class/scsi_host/host*/link_power_management_policy; do opt "$i" medium_power; done
for dev in $(awk '/^\/dev\/sd/ {print $1}' /etc/mtab); do run mount -o remount,relatime "$dev"; done
for dev in $(awk '/^\/dev\/sd/ {print $1}' /etc/mtab); do run blockdev --setra 256 "$dev"; done
for dev in $(awk '/^\/dev\/sd/ {print $1}' /etc/mtab); do run hdparm -B 254 -S 253 "$dev"; done

# Sound card powersave
opt /sys/module/snd_hda_intel/parameters/power_save 0
opt /sys/module/snd_hda_intel/parameters/power_save_controller N
opt /sys/module/snd_ac97_codec/parameters/power_save 0

# wlan0/eth0 powersave
run iw dev wlan0 set power_save off

# Screen powersave
for i in /sys/class/backlight/acpi_video*/brightness; do opt "$i" "$(brightness_scale 5)"; done
opt /sys/module/i915/parameters/i915_enable_rc6 0

# Disable webcam
load_mod uvcvideo
load_mod videodev
load_mod nouveau

# Disable bluetooth
load_mod btusb
load_mod bluetooth
