#!/usr/bin/env bash
# powerdown-utils

# turn on kernel options
opt() {
  [[ -w $1 && -r $1 ]] || return
  echo $2 | tee $1 &>/dev/null || echo "[powerdown] cannot write $2 to $1"
}

# unload kernel module
unload() {
  has $1 || return
  loaded $1 || return
  rmmod -w $1 &>/dev/null || echo "[powerdown] cannot unload module $1"
}

# load kernel module
load() {
  has $1 || return
  loaded $1 && return
  modprobe $1 &>/dev/null || echo "[powerdown] cannot load module $1"
}

# module exists
has() {
  modinfo $1 &>/dev/null
  return $?
}

# module loaded
loaded() {
  [[ $(lsmod | cut -f 1 -d " " | grep "^$1$") != "" ]] && return 0 || return 1
}

# command
run() {
  $@ &> /dev/null || echo "[powerdown] cannot run $@"
}

# get current power usage
display_power() {
  mWh=$(($(cat /sys/class/power_supply/BAT0/power_now)/1000))
  echo "[powerdown] using $mWh mWh"
}

# get readahead
display_readahead() {
  echo " - $1 readahead: $(blockdev --getra $1)"
}

check () {
  [[ -w $1 && -r $1 ]] || return
  echo " - $1: $(cat $1)"
}

display_module() {
  has $1 || return
  echo -n " - $1 "
  loaded $1 && echo "loaded" || echo "not loaded"
}

display_wireless() {
  control=$(iwconfig $1 | grep "Power Management" | cut -d : -f 2)
  echo " - $1 power management: $control"
}

hibernate_offset() {
  filefrag -v /hibernate | awk '{print $3}' | awk 'NR==4'
}

root_partion() {
  df / | awk '{print $1}' | awk 'NR==2'
}

resume_boot_option() {
  echo "'resume=$(root_partion) resume_offset=$(hibernate_offset)'"
}
