#!/usr/bin/env bash
# powerdown - get energy usage
# get current power usage
current_power() {
	mWh=$(($(cat /sys/class/power_supply/BAT0/power_now)/1000))
	echo "[powerdown] using $mWh mWh"
}

current_power
