#!/usr/bin/env bash
# powerdown-utils

# turn on kernel options
opt() {
  [[ -f $1 ]] || return
  # for disable cpu
  [[ $(cat $1) == $2 && $1 == /sys/devices/system/cpu/cpu*/online ]] && return
  echo $2 | tee $1 &>/dev/null || echo "[powerdown] cannot write $2 to $1"
}

# unload kernel module
unload() {
  modinfo $1 &>/dev/null || return
  [[ $(lsmod | cut -f 1 -d " " | grep "^$1$") == "" ]] && return
  rmmod -w $1 &>/dev/null || echo "[powerdown] cannot unload module $1"
}

# load kernel module
load() {
  modinfo $1 &>/dev/null || return
  [[ $(lsmod | cut -f 1 -d " " | grep "^$1$") == "" ]] || return
  modprobe $1 &>/dev/null || echo "[powerdown] cannot load module $1"
}

# command
run() {
  $@ &> /dev/null || echo "[powerdown] cannot run $@"
}
