#!/usr/bin/env bash
# powerd - simple daemon

if [[ $EUID != 0 ]]; then
  echo "[powerdown] must be run as root"
  exit 1
fi

if [[ -f /sys/class/power_supply/AC0/online ]]; then
    AC_PATH=/sys/class/power_supply/AC0/online
elif [[ -f /sys/class/power_supply/AC/online ]]; then
    AC_PATH=/sys/class/power_supply/AC/online
else
    echo "cannot detect battery or ac"
    exit 1
fi

trap "echo 'powerd got SIGINT...'; usb-unbind; exit 0" SIGINT

echo "start powerd..."

while true; do
    new=$(cat $AC_PATH)
    if [[ $old != $new ]]; then
        if [[ $new == 1 ]]; then
            echo "using AC, performance mode"
            powerup &>/dev/null
        else
            echo "using BAT, powersave mode"
            powerdown &>/dev/null
        fi
    fi
    old=$new

    sleep 10
done
