#!/bin/bash

[[ $EUID != 0 ]] && exit 1

echo "$(date): power_supply $1" >> /tmp/power_supply

if [[ "$1" == on ]]; then
    /usr/bin/powerup
elif [[ "$1" == off ]]; then
    /usr/bin/powerdown
fi

exit 0
