#!/usr/bin/env bash

if [[ $EUID != 0 ]]; then
  echo "[powerdown] must be run as root"
  exit 1
fi

if [[ ! -f /hibernate ]]; then
  echo "[powerdown] hibernate is not ready yet"
  exit 1
fi

source /usr/lib/powerdown-functions

sync
opt /proc/sys/vm/drop_caches 3

intv=600
# after 10 minutes, it will wake up and go to hibernate mode
now=$(date -u +%s)
rtcwake -u -m mem -s $intv
diff=$(($(date -u +%s) - $now))
(( $diff >= $intv )) && suspend-to-disk
