#!/usr/bin/env bash

if [[ $EUID != 0 ]]; then
  echo "[powerdown] must be run as root"
  exit 1
fi

source /usr/lib/powerdown-functions
lock

if ! can_suspend_to_disk; then
    echo "[powerdown] your first time to use powerdown hibernate"
    echo "creating 2GB /hibernate"
    dd if=/dev/zero of=/hibernate bs=2M count=1024
    chmod 600 /hibernate
    mkswap /hibernate
    exit 1
fi

echo "1. Please add '$(resume_boot_option)' to the boot configuration"
echo
echo "2. Please add 'resume' hook to /etc/mkinitcpio.conf right in front of 'filesystem' hook"
echo "Run 'mkinitcpio -p linux' to regenerate kernel image"
echo
echo "Hibernate and resume will take a long time. Have a cup of coffee..."

[[ -f /hibernate ]] && swapon /hibernate
sync
opt /sys/power/state disk
[[ -f /hibernate ]] && swapoff /hibernate
