#!/usr/bin/env bash

if [[ $EUID != 0 ]]; then
  echo "[powerdown] must be run as root"
  exit 1
fi

if [[ ! -f /hibernate ]]; then
  echo "[powerdown] hibernate is not ready yet"
  exit 1
fi

source /usr/lib/powerdown-functions

sync
opt /proc/sys/vm/drop_caches 3

# after 10 minutes, it will wake up and go to hibernate mode
rtcwake -u -m mem -s 600
suspend-to-disk
