#!/usr/bin/env bash

if [[ $EUID != 0 ]]; then
    echo "[powerdown] must be run as root"
    exit 1
fi

source /usr/lib/powerdown-functions

if ! can_suspend_to_disk; then
    echo "[powerdown] hibernate is not ready yet"
    exit 1
fi

lock
sync

intv=600
# after 10 minutes, it will wake up and go to hibernate mode
now="$(date -u +%s)"
rtcwake -u -m mem -s "$intv"
diff="$(($(date -u +%s) - $now))"
if (( $diff >= $intv )); then
    [[ -f /hibernate ]] && swapon /hibernate
    opt /sys/power/state disk
    [[ -f /hibernate ]] && swapoff /hibernate
fi
