#!/usr/bin/env bash

if [[ $EUID != 0 ]]; then
  echo "[powerdown] must be run as root"
  exit 1
fi

source /usr/lib/powerdown-functions

sync
opt /proc/sys/vm/drop_caches 3

usb-unbind

echo mem > /sys/power/state

usb-bind
